version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5452:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local